# Generated by Django 3.2.5 on 2021-09-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_orderitem_portfolio_product_shippingadress'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='device',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ip',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
