# Generated by Django 3.2.5 on 2021-09-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210919_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='device',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
