# Generated by Django 3.2.5 on 2021-09-19 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_customer_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='device',
        ),
    ]
