# Generated by Django 3.2.5 on 2021-09-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_customer_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='ip',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
