# Generated by Django 3.2.5 on 2021-09-25 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='is_current',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='from_detail',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='to_order',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
