# Generated by Django 3.2.5 on 2021-09-25 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210925_0233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='from_detail',
        ),
    ]
