# Generated by Django 3.2.5 on 2021-09-25 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_orderitem_from_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(blank=True, null=True, upload_to='img/products/second')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('date_uploaded', models.DateTimeField(auto_now=True, null=True, verbose_name='modified')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
