# Generated by Django 3.2.5 on 2021-09-26 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='ip',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='name',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
