# Generated by Django 3.2.5 on 2021-09-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20210926_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingadress',
            name='phone',
            field=models.PositiveIntegerField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shippingadress',
            name='state',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
