# Generated by Django 3.2.5 on 2021-09-27 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20210927_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingadress',
            name='phone',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
