# Generated by Django 3.2.5 on 2021-09-27 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_shippingadress_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingadress',
            name='city',
        ),
    ]
